imageapi/urls.py
from django.urls import path
from .views import MediaViewSet, like_post, UserViewSet, follow_user, GalleryViewSet

app_name = 'imageapi'

urlpatterns = [
    path('', MediaViewSet, name='post-list'),
    path('', UserViewSet, name='user-details'),
    path('gallery', GalleryViewSet, name='gallery-list'),
    path('searchResults', UserViewSet, name='search-results'),
    path('like/', like_post, name="like-post"),
    path('follow/', follow_user, name="follow-user")
]

imagesharingapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from imagesharingapp import views
from django.views.static import serve



urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('register/', views.register, name='register'),
    path('posts/', include('imageapi.urls', namespace='posts'))
]

urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT) 
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

imageapi/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Media(models.Model):
    caption = models.CharField(max_length=100)
    liked = models.ManyToManyField(User,default=None, blank=True)
    image = models.ImageField(upload_to='static/images', default='https://www.fillmurray.com/640/360')
    dateuploaded= models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')

    def __str__(self):
        return str(self.caption)
    
    @property
    def num_likes(self):
        return self.liked.all().count()

LIKE_CHOICES=(
    ('like','like'),
    ('unlike','unlike'),
)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Media, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, default='Like', max_length=10)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followedby = models.ManyToManyField(User,default=None, blank=True, related_name='followedby')
    description = models.CharField(max_length=100)

    @property
    def num_followers(self):
        return self.followedby.all().count()

FOLLOW_CHOICES=(
    ('follow','follow'),
    ('unfollow','unfollow'),
)

class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    followee = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followee')
    value = models.CharField(choices=LIKE_CHOICES, default='Like', max_length=10)

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

imageapi/views.py
from django.shortcuts import render, redirect
from rest_framework import viewsets
from rest_framework.response import Response
from imageapi.models import Media, Like, UserProfile, Follow
from imageapi.serializers import MediaSerializer
from django.db.models import Count
from django.contrib.auth.models import User

# Create your views here.

def MediaViewSet(request):
    queryset = Media.objects.all().annotate(num_like=Count('liked')).order_by('-num_like')
    user = request.user
    context= {
    'queryset': queryset,
    'user': user,
    }
    return render(request, 'posts/main.html', context)

def GalleryViewSet(request):
    user = request.user
    queryset = Media.objects.filter(author = user).annotate(num_like=Count('liked')).order_by('-num_like')
    context= {
    'queryset': queryset,
    'user': user,
    }
    return render(request, 'posts/gallery.html', context)


def UserViewSet(request):
    user = request.user
    userqueryset =User.objects.all()

    context= {
    'userqueryset': userqueryset,
    'user': user,
    }
    return render(request, 'posts/searchResults.html', context)

def like_post(request):
    user=request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Media.objects.get(id=post_id)

        if user in post_obj.liked.all():
           post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)
        like,created = Like.objects.get_or_create(user=user, post_id=post_id)
        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value='Like'
            like.save()
    return redirect('posts:post-list')



def follow_user(request):
    user=request.user
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        user_obj = UserProfile.objects.get(user_id=user_id)

        if user in user_obj.followedby.all():
            user_obj.followedby.remove(user)
        else:
            user_obj.followedby.add(user)
        follow,created = Follow.objects.get_or_create(user=user, user_id=user_id)
        if not created:
            if follow.value == 'follow':
                follow.value = 'unfollow'
            else:
                follow.value='follow'
            follow.save()
    return redirect('posts:follow-user')

def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    user_name = self.request.GET.get('search', '')
    context['all_search_results'] = User.objects.filter(username__icontains=user_name )
    return context

imagesharingapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

def login_redirect(request):
    return redirect('/account/login')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('http://localhost:3000/')
    else:
        form = UserCreationForm()
        args = {'form' : form}
        return render(request, 'accounts/reg_form.html', args)

imageapi/templates/accounts/login.html
{% extends 'core.html' %}
{% block body %}
<div class="container">
    <h1>Welcome</h1>
    <p>
        Please login to continue
    </p>

    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

imageapi/templates/accounts/logout.html
{% extends 'core.html' %}
{% block body %}
<div class="container">
    <h1>Logged Out</h1>
    <p>
        You have logged out
    </p>
</div>
{% endblock %}

imageapi/templates/accounts/reg_form.html
{% extends 'core.html' %}

{% block body %}
<div class='container'>
<h1>Welcome</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Submit</button>
</form>
</div>
{% endblock %}

imageapi/templates/core.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <a class="navbar-brand" href="/posts">Image Sharing Application</a>
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            
                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/register">Register</a>
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="/logout">logout</a>       
                            {% else %}
                            <a class="nav-link" href="/login">login</a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            <form class="form-inline my-2 my-lg-0 ml-auto" action="{% url 'posts:search-results' %}" method="GET">
                                <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                              </form>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        {% block body %}
        <h1>Base</h1>
        {% endblock %}
    </body>
</html>

imageapi/templates/posts/gallery.html
{% extends 'core.html' %}

{% block body %}

<div class="container">
    {% if user.is_authenticated %}
        <h5 class="card-title">Welcome, {{ user.username }}. These are your photos.</h5>
    {% else %}
        <h5 class="card-title">Welcome, new user. Please log in.</h5>
    {% endif %}




    {% for obj in queryset%}
    <div class="card" style="width: 45rem; margin-top:25%;">
        {% load static %}<img class="card-img-top" src="{{obj.image.url }}">
        <div class="card-body">
        <h5 class="card-title">{{obj.caption}}</h5>
        <form action="{% url 'posts:like-post'%}" method ='POST' class="ui form">
            {% csrf_token %}
            <input type='hidden' name='post_id' value="{{obj.id}}">
            {% if user not in obj.liked.all %}
                <button class="btn btn-success" type='submit'>Like</button>
            {% else %}
                <button class="btn btn-danger" type='submit'>Unike</button>
            {% endif %}
        </form>
        <strong>{{obj.liked.all.count}} likes</strong>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}
        

imageapi/templates/posts/main.html
{% extends 'core.html' %}

{% block body %}

<div class="container">
    <div class="card" style="width: 45rem; margin-top:10%;">
        <div class="card-body">
            {% if user.is_authenticated %}
                <h5 class="card-title">Welcome, {{ user.username }}. Thanks for logging in.</h5>
            {% else %}
                <h5 class="card-title">Welcome, new user. Please log in.</h5>
            {% endif %}
            <form action="gallery">
                <input type="submit" value="My Images" />
            </form>
        
        </div>
    </div>
        <div class="card-deck" style="border: 1px solid;">
            <h2>Content Feed</h2>
            {% for obj in queryset%}
            <div class="row">
                <div class="col-sm-6">
                    <div class="card" style="width: 45rem; margin-top:25%;">
                        {% load static %}<img class="card-img-top" src="{{obj.image.url }}">
                        <div class="card-body">
                        <h5 class="card-title">{{obj.caption}}</h5>
                        <form action="{% url 'posts:like-post'%}" method ='POST' class="ui form">
                            {% csrf_token %}
                            <input type='hidden' name='post_id' value="{{obj.id}}">
                            {% if user not in obj.liked.all %}
                                <button class="btn btn-success" type='submit'>Like</button>
                            {% else %}
                                <button class="btn btn-danger" type='submit'>Unike</button>
                            {% endif %}
                        </form>
                        <strong>{{obj.liked.all.count}} likes</strong>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor%}
        </div>
</div>
{% endblock %}

imageapi/templates/posts/searchResults.html
{% extends 'core.html' %}
{% block body %}

<div class="container">
{% for obj in userqueryset%}
<h5>{{obj.get_username}}</h5>
{% endfor %}
</div>
{% endblock %}